// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {app} from '../models';

export function CreateWorkspaceTemplate(arg1:string):Promise<void>;

export function DeleteExampleFromFolder(arg1:string,arg2:string):Promise<void>;

export function DetectGoPath():Promise<string>;

export function FormatCode(arg1:string):Promise<string>;

export function GetConfig():Promise<config.Config>;

export function Greet(arg1:string):Promise<string>;

export function LoadExamplesFromFolder(arg1:string):Promise<Array<app.CodeExample>>;

export function RunCode(arg1:string):Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function SaveExampleToFolder(arg1:string,arg2:app.CodeExample):Promise<void>;

export function SelectWorkspaceFolder():Promise<string>;

export function ValidateGoPath(arg1:string):Promise<boolean>;
