// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWorkspaceTemplate(arg1) {
  return window['go']['app']['App']['CreateWorkspaceTemplate'](arg1);
}

export function DeleteExampleFromFolder(arg1, arg2) {
  return window['go']['app']['App']['DeleteExampleFromFolder'](arg1, arg2);
}

export function DetectGoPath() {
  return window['go']['app']['App']['DetectGoPath']();
}

export function FormatCode(arg1) {
  return window['go']['app']['App']['FormatCode'](arg1);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function LoadExamplesFromFolder(arg1) {
  return window['go']['app']['App']['LoadExamplesFromFolder'](arg1);
}

export function RunCode(arg1) {
  return window['go']['app']['App']['RunCode'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SaveExampleToFolder(arg1, arg2) {
  return window['go']['app']['App']['SaveExampleToFolder'](arg1, arg2);
}

export function SelectWorkspaceFolder() {
  return window['go']['app']['App']['SelectWorkspaceFolder']();
}

export function ValidateGoPath(arg1) {
  return window['go']['app']['App']['ValidateGoPath'](arg1);
}
